config:
  token: <%= ENV['CODE_STATS_TOKEN'] %>
  ci: 'CIRCLECI'
  url: <%= ENV['CODE_STATS_URL'] %>
metrics:
  rubycritic:
    name: 'Code Quality'
    enabled: true
    minimum: 70
    upload_report: false
  simplecov:
    name: 'Code Coverage'
    enabled: true
    minimum: 10
