scss_files: "app/assets/stylesheets/"

linters:

  HexNotation:
    enabled: true
    style: uppercase

  LeadingZero:
    enabled: true
    style: include_zero

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 5

  PlaceholderInExtend:
    enabled: false

  PropertyUnits:
    enabled: false

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  TrailingZero:
    enabled: true

  VendorPrefix:
    enabled: true

  ZeroUnit:
    enabled: true
