development: &development
  github_client_id: d879adce523cd9ac3c92
  github_client_secret: ae20346b50ca51396cc9c3742612f90c3877023e
  github_webhook_url: http://3adf942c.ngrok.io/github_pull_requests
  mailer_address: ''
  mailer_authentication: ''
  mailer_domain: ''
  mailer_host: ''
  mailer_password: ''
  mailer_port: ''
  mailer_user_name: 'no-reply@training.wolox.com.ar'
  secret_key_base: e369575030a3ac3c396ccb152187c43e61e03721a910e5a90a1153c0f06b04c2a2b750ffb0020152a6580c261cb86ae11936f0ea2deec6380012b33d35b7fd3c
  allowed_organizations: <%= ENV.fetch('ALLOWED_ORGS', 'wolox').split(',') %>

test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  email_recipients_interceptors: <%= ENV['EMAIL_RECIPIENTS_INTERCEPTOR'] %>
  github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  github_webhook_url: <%= ENV['GITHUB_WEBHOOK_URL'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  mailer_authentication: <%= ENV['MAILER_AUTHENTICATION'] %>
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>
  mailer_user_name: <%= ENV['MAILER_USER_NAME'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  allowed_organizations: <%= ENV.fetch('ALLOWED_ORGS', '').split(',') %>
