development: &development
  secret_key_base: e369575030a3ac3c396ccb152187c43e61e03721a910e5a90a1153c0f06b04c2a2b750ffb0020152a6580c261cb86ae11936f0ea2deec6380012b33d35b7fd3c

test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>
  trello_url: <%= ENV["TRELLO_URL"] %>
  email_recipients_interceptors: <%= ENV["EMAIL_RECIPIENTS_INTERCEPTOR"] %>
